# site.yml
- name: Deploy Fibi Infra
  hosts: all
  become: yes
  roles:
    - elasticsearch
    #- logstash
    #- mysql
    #- tomcat
    #- mysql_script_exec
    #- download_artifacts
    #- jar-services
    #- deployment
    #- apache

