---

- name: Filter services to deploy based on build_list
  set_fact:
    filtered_services: "{{ services | selectattr('name', 'in', build_list) | list }}"

- name: Create systemd service files
  template:
    src: service.j2
    dest: "/etc/systemd/system/{{ item.name }}.service"
  loop: "{{ filtered_services }}"
  notify: Reload systemd

- name: Reload systemd manually
  command: systemctl daemon-reload
  become: yes

