---

#- name: Load services_to_deploy from file
#  include_vars:
#    file: jar_services.yml

- name: Create systemd service files
  template:
    src: service.j2
    dest: "/etc/systemd/system/{{ item.name }}.service"
  loop: "{{ services }}"
  notify: Reload systemd

- name: Reload systemd manually
  command: systemctl daemon-reload
  become: yes

