---

##download_artifacts

all_artifacts:
  - { name: "fibi-api-gateway", path: "backend/fibi40", extension: "jar" }
  - { name: "fibi-auth-service", path: "backend/fibi40", extension: "jar" }
  - { name: "fibi-service-request", path: "backend/fibi40", extension: "jar" }
  - { name: "fibi-base", path: "backend/fibi40", extension: "war" }
  - { name: "fibi-config-server", path: "backend/fibi40", extension: "jar" }
  - { name: "fibi", path: "frontend/fibifrontend", extension: "zip" }
  - { name: "fibi-service-registry", path: "backend/fibi40", extension: "jar" }
  - { name: "fibi-agreement", path: "backend/fibi40", extension: "jar" }
  - { name: "fibi-form-builder", path: "backend/fibi40", extension: "jar" }
  - { name: "fibi-graph-connect", path: "backend/fibi40", extension: "jar" }
  - { name: "fibi-elasticsync", path: "backend/elasticsync", extension: "war" }
  - { name: "fibi-rbmq-router", path: "backend/fibiqueue", extension: "jar" }
  - { name: "fibi-consumer", path: "backend/fibiqueue", extension: "jar" }


