---

##download_artifacts

build_list:
  - fibi-api-gateway
  - fibi-auth-service
  - fibi-base
  - fibi-config-server
  - fibi-service-request
  - fibi-service-registry
  - fibi
  - fibi-agreement
    #- fibi-coi-connect
  - fibi-form-builder
    #- fibi-notification-service
  - fibi-graph-connect
    #- fibi-docusign
    #- fibi-attachement-pdf-merger
  - fibi-elasticsync
    #- fibi-coi
  - fibi-rbmq-router
  - fibi-consumer
