---

services_to_deploy:
  - fibi-server-registry.service
  - fibi-config-server.service
  - fibi-auth-service.service
  - fibi-api-gateway.service
  - fibi-service-request.service
  - fibi-agreement.service
  - tomcat.service
