---

- name: Load setenv.sh file with environment variables from file
  include_vars:
    file: env_vars.yml


- name: Set permissions for Tomcat
  file:
    path: "{{ tomcat_home }}"
    state: directory
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    recurse: yes

- name: Create setenv.sh file with environment variables
  template:
    src: setenv.sh.j2
    dest: "{{ tomcat_home }}/bin/setenv.sh"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: '0755'
      #no_log: true 

- name: Ensure Tomcat bin directory scripts are executable
  file:
    path: "{{ tomcat_home }}/bin"
    state: directory
    mode: '0755'
    recurse: yes

- name: Ensure JAVA Heap is set in catalina.sh
  lineinfile:
    path: "{{ tomcat_home }}/bin/catalina.sh"
    line: 'export CATALINA_OPTS="{{ catalina_opts }}"'
    insertbefore: '# Check for the deprecated LOGGING_CONFIG'
    state: present

- name: Get and set JAVA_HOME
  shell: "update-alternatives --query java | awk '/Value: / {print $2}' | sed 's:/bin/java::'"
  register: java_home_result
  changed_when: false

- name: Display JAVA_HOME
  debug:
    msg: "JAVA_HOME is set to {{ java_home_result.stdout }}"

