---

- name: Replace elasticsearch.yml with templated version
  template:
    src: templates/elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: '06460'

- name: Configure Elasticsearch JVM heap size
  lineinfile:
    path: /etc/elasticsearch/jvm.options
    regexp: '^-Xms'
    line: "-Xms{{ es_heap_size }}"
    state: present

- name: Configure Elasticsearch JVM max heap size
  lineinfile:
    path: /etc/elasticsearch/jvm.options
    regexp: '^-Xmx'
    line: "-Xmx{{ es_heap_size }}"
    state: present

