---
- name: Add Elasticsearch GPG key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elasticsearch repository
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Elasticsearch
  apt:
    name: "elasticsearch={{ elastic_version }}"
    state: present

