---

#- name: Add Elasticsearch GPG key
#  apt_key:
#    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
#    state: present

#- name: Add Elasticsearch repository
#  apt_repository:
#    repo: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"
#    state: present

- name: Download Elasticsearch GPG key and save as binary keyring
  ansible.builtin.shell: >
    wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch |
    gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg
  args:
    creates: /usr/share/keyrings/elasticsearch-keyring.gpg

- name: Add Elasticsearch APT repository
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/elastic-8.x.list
    content: "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main\n"
    mode: '0644'

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Elasticsearch
  apt:
    name: "elasticsearch={{ elastic_version }}"
    state: present

