---
mysql_version: "8.0.35-1ubuntu22.04_amd64.deb-bundle"
mysql_download_url: "https://cdn.mysql.com/archives/mysql-8.0/mysql-server_{{ mysql_version }}.tar"
mysql_install_dir: "/usr/local/mysql"
mysql_data_dir: "/var/lib/mysql"
mysql_dependencies:
  - libaio1
  - libncurses5
  - libnuma1
  - libmecab2
mysql_root_password: "Polus@123"
mysql_db_name: "fibi"
mysql_user: "fibiuser"
mysql_user_password: "Polus@123"


