---
# defaults file for mysql_script_exec

#git_branch: "Fibi-Dev/Demo/Jenkins"
git_branch: "Fibi-Vanilla-5.5"
git_dest: "/tmp/mysql-scripts/"
work_path: "/tmp/mysql-scripts/Fibi-5.4/"
mysql_host: "localhost"
mysql_user: "fibiuser"
mysql_password: "Polus@123"
mysql_port: 3306
mysql_database: "fibi"
sql_script: "all.sql"
