---
# defaults file for mysql_script_exec

#git_repo: "https://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@github.com/Polus-Software/fibi40-db.git"
git_branch: "Fibi-Dev/Demo/Jenkins"
git_dest: "/tmp/mysql-scripts/"
work_path: "/tmp/mysql-scripts/"
mysql_host: "localhost"
mysql_user: "fibiuser"
mysql_password: "Polus@123"
mysql_port: 3306
mysql_database: "fibi"
sql_script: "all.sql"
